#!/bin/sh
#efibootmgr --disk /dev/sda --part 1 --create --label 'oasis' --loader linux --unicode 'root=/dev/sda2 init=/bin/sinit ro quiet' --verbose

efibootmgr -c -d /dev/sda -p 1 -l /linux -L oasis "root=/dev/sda2 init=/bin/sinit ro"
